title: Tim Petri
url: "https://timpetri.com"
author: "Tim Petri"
keywords: "tim,petri,code,google,wpi,tech,software"
github: timpetri
twitter: timpetri
email: me@timpetri.com

exclude: [
  ".gitignore",
  "CNAME",
  "LICENSE",
  "README",
]

# Conversion
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM # Adds classes to my markdown
  syntax_highlighter: rouge

permalink: pretty
timezone: America/New_York

sass:
  style: compressed

# Here, we are scoping the values to any file that exists in the path scope
# Without a scope tag this would apply to things such as css as well.
defaults:
  -
    scope:
      path: "" # Filter, can be globbed, empty = all files in the project.
      type: pages # pages, posts, drafts or any custom collection in your site
    values:
      layout: "base"
  -
    scope:
      path: "blog"
      type: "posts"

    values: 
      layout: "post"
      author: "Tim Petri"